version: "3.5"
services:

  app:
    build:
      target: development
    image: nicholasodonnell/odo-stream:dev
    volumes:
      - ./next.config.js:/app/next.config.js
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./public:/app/public
      - ./src:/app/src
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./tsconfig.json:/app/tsconfig.json
